#!/bin/bash

set -e

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

pkgname="libevent"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
openssl_prefix="$here/openssl/dist"
openssl_include="$openssl_prefix/include"
openssl_lib="$openssl_prefix/lib"
if ! [ -x configure ] ; then
    ./autogen.sh || fail "Could not configure $pkgname"
fi
if ! [ -r config.status ] ; then
    ./configure \
        $AUTOCONF_FLAGS \
        --prefix="$here/$pkgname/dist" \
        --disable-shared \
        --enable-static \
        --with-pic \
        --disable-samples \
        --disable-libevent-regress \
        CPPFLAGS=-I"$openssl_include" \
        LDFLAGS=-L"$openssl_lib" || fail "Could not configure $pkgname"
fi
make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
popd
