#!/bin/bash

set -e

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

pkgname="tor"
info "Building $pkgname..."

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"

LDFLAGS="-s"
EXTRA_FLAGS=""
OPENSSL_FLAGS=""
CONFIGURE_CPPFLAGS=""

if [ "$BUILD_TYPE" = "windows" ] ; then
    LIBS="-lcrypt32 -lgdi32"
fi

# Detect OpenSSL: custom build > Homebrew > system
if [ -f "$here/openssl/dist/lib/libssl.a" ] || [ -f "$here/openssl/dist/lib/libssl.so" ]; then
    openssl_dir="$here/openssl/dist"
    info "Using custom OpenSSL at: $openssl_dir"
    OPENSSL_FLAGS="--enable-static-openssl --with-openssl-dir=$openssl_dir"
    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
    LDFLAGS="-L$openssl_dir/lib -s"
    if [ "$BUILD_TYPE" != "darwin" ]; then
        EXTRA_FLAGS="$EXTRA_FLAGS --enable-static-tor"
    fi
elif [ -d "/opt/homebrew/opt/openssl@3" ]; then
    openssl_dir="/opt/homebrew/opt/openssl@3"
    info "Using Homebrew OpenSSL at: $openssl_dir"
    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
    LDFLAGS="-L$openssl_dir/lib -s"
elif [ -d "/opt/homebrew/opt/openssl@1.1" ]; then
    openssl_dir="/opt/homebrew/opt/openssl@1.1"
    info "Using Homebrew OpenSSL at: $openssl_dir"
    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
    LDFLAGS="-L$openssl_dir/lib -s"
elif [ -d "/usr/local/opt/openssl@3" ]; then
    openssl_dir="/usr/local/opt/openssl@3"
    info "Using Homebrew OpenSSL at: $openssl_dir"
    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
    LDFLAGS="-L$openssl_dir/lib -s"
elif [ -d "/usr/local/opt/openssl@1.1" ]; then
    openssl_dir="/usr/local/opt/openssl@1.1"
    info "Using Homebrew OpenSSL at: $openssl_dir"
    OPENSSL_FLAGS="--with-openssl-dir=$openssl_dir"
    CONFIGURE_CPPFLAGS="CPPFLAGS=-I$openssl_dir/include"
    LDFLAGS="-L$openssl_dir/lib -s"
else
    # System OpenSSL (Linux) - let configure auto-detect
    # Do NOT use --enable-static-tor here as it forces enable_static_openssl=yes
    # which requires --with-openssl-dir to be set
    info "Using system OpenSSL (auto-detected by configure)"
fi

if ! [ -x configure ] ; then
    ./autogen.sh || fail "Could not configure $pkgname"
fi

# Force reconfigure to ensure latest options are applied
rm -f config.status

./configure \
    $AUTOCONF_FLAGS \
    $CONFIGURE_CPPFLAGS \
    LDFLAGS="$LDFLAGS" \
    --prefix="$here/$pkgname/dist" \
    --disable-system-torrc \
    --disable-manpage \
    --disable-html-manual \
    --disable-asciidoc \
    --enable-static-libevent --with-libevent-dir=$here/libevent/dist \
    $OPENSSL_FLAGS \
    --enable-static-zlib --with-zlib-dir=$here/zlib/dist \
    --disable-systemd \
    --disable-lzma \
    --disable-zstd \
    --disable-unittests \
    --disable-seccomp \
    --disable-libscrypt \
    --disable-module-dirauth \
    --disable-module-relay \
    $EXTRA_FLAGS || fail "Could not configure $pkgname"

make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
binary="tor"
if [ "$BUILD_TYPE" = "wine" ] ; then
    binary="tor.exe"
fi
host_strip "$here/$pkgname/dist/bin/$binary"
mkdir -p "$here/../electroncash/tor/bin"
cp -fpv "$here/$pkgname/dist/bin/$binary" "$here/../electroncash/tor/bin/." || fail "Could not copy the $pkgname binary to its destination"
$SHA256_PROG "$here/$pkgname/dist/bin/$binary"
info "$binary has been placed in the 'electroncash' folder."
popd
